### PR TITLE
Combine two of the bullet points in the final exercise.

### PR DESCRIPTION
**Pull request by hockeybuggy**
Based on the file `reference/final_exercise.py` and the French slides the question is asking for registrants for either "girls learning code" or "kids learning code". The English slides had these as separate bullets which I just had a student confused by.

Changing to try to clarify. If we would rather change the exercise for simplicity let me know and I would be happy to change the french slides and exercise. 😄

### CODE REVIEW

**Comment by hockeybuggy** [comment]
Hey, Just following up on my PRs. Does anyone have any thoughts on this?

**Comment by hockeybuggy** [comment]
Hello. Just following up. I would be happy to close this if people would prefer. 😸

**Comment by jessynd** [comment]
Thanks so much @hockeybuggy. Sorry for the huge delays in merging this!

**Comment by hockeybuggy** [comment]
No worries. Thank you!

**Pull request merged**
