### PR TITLE
Use `with` for file I/O

### PR DESCRIPTION
**Pull request by AlainODea**
Python's `with` statement removes the need for manually closing files
in most cases.  This is particularly valuable for avoiding surprises
when writing files.

I had to play around with the indentation of the affected slides to get
it to display correctly.

This includes my "BetterOfflineSupport" branch changes as well, but I felt it
wise to keep them separated in case this is too radical a change to
be accepted.

### CODE REVIEW

**Comment by bchhun** [comment]
It was also the first thing that popped in my mind when I reached the file manipulation section but after second thought, I believe it's ok to leave it as it is just to enforce the "be precise in what you tell the computer" awareness.

**Comment by evidens** [comment]
I nearly always use the `with` statement in my own code, but I like to at least expose new learners to what's going on in the system. That's why I opted out of `with` when I wrote up the exercises.

**Comment by christinatruong** [comment]
I think changing to the `with` statement this close to Code Day is too much of a change.  And also, as this is a beginner focused workshop, as @bchhun said, being precise with the idea of giving instructions to the computer is more in line with the content strategy.  We can only teach so much in one day! Thanks for the suggestion though.

**Comment by alain-odea-vgh** [comment]
@evidens @christinatruong thank you for the feedback.  I'm going to have words my Emacs config about eating the trailing spaces ;)

I agree with going for explicit I/O here.  It makes working in the console easier and drives home more of what is actually happening :)

**Comment by christinatruong** [comment]
@alain-odea-vgh  Always comes up when using Markdown :) I should probably add some explicit info re trailing spaces to the readme.  I have some general cleanup to do with our repos anyway so I'll be sure to add that.  Thanks again!

**Pull request closed without merging**
