### PR TITLE
Change typo in an event name

### PR DESCRIPTION
**Pull request by hockeybuggy**
Not 100% if this is a typo or the event just had a weird name. 😄 

Feel free to close if this is correct.

### CODE REVIEW

**Comment by hockeybuggy** [comment]
Huh. Perhaps not a typo in the dataset: http://www.eventbrite.ca/e/kid-learning-code-intro-to-photoshop-for-teens-at-george-brown-college-tickets-9662692373#

**Comment by hockeybuggy** [comment]
Does anyone have feelings on this? It strikes me a bit of a curveball in the project component of the lesson. I can't decide if that's bad for learners who are struggling or good for learners who could use a challenge.

**Comment by jessynd** [comment]
There was definitely a typo in that eventbrite event but I'm not sure about which way to go with this. We are having a meeting of the Python Advisory Council later this week to discuss the content in general. Would you like to join us @hockeybuggy? Your feedback would be most welcome. It's via google hangouts and I'd be happy to include you.

**Comment by hockeybuggy** [comment]
Ok cool. I am happy to close this then. 😄 

Thank you, but no thank you @jessynd.

**Pull request closed without merging**
